### ISSUE TITLE
Create CA private key needs a directory

### ISSUE THREAD

**Issue by bbaassssiiee** [cogini/ansible-role-postgresql-ca#2]
Maybe you did not commit or push the files directory?

```yaml
  - name: Create CA private key
    command: >
      openssl genrsa -aes256
      -out {{ role_path }}/files/postgresql-ca-key.pem
      -passout "pass:{{ postgresql_ca_ca_pass }}" {{ postgresql_ca_ca_key_bits }}
    args:
      creates: "{{ role_path }}/files/postgresql-ca-key.pem"
    when: not postgresql_ca_ca_key.stat.exists
    no_log: postgresql_ca_no_log
```
